import {NextRequest, NextResponse} from 'next/server'
import {verifyMobileLoginToken} from '../utils'
import {db} from '@/db/drizzle'
import {user as userTable, session as sessionTable} from '@/db/schema'
import {eq} from 'drizzle-orm'
import {getCookies} from 'better-auth/cookies'
import {auth} from '@/lib/auth/config'

/**
 * Generate a secure random token matching better-auth's format
 */
const generateSecureToken = (length: number): string => {
	const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
	const array = new Uint8Array(length)
	crypto.getRandomValues(array)
	return Array.from(array, byte => chars[byte % chars.length]).join('')
}

/**
 * Sign a cookie value the same way Better Auth expects (`better-call`):
 * - compute HMAC-SHA256 over the raw token using BETTER_AUTH_SECRET
 * - append as `${token}.${base64(signature)}`
 * - encodeURIComponent() the whole value for safe cookie transport
 */
const signCookieValue = async (value: string, secret: string): Promise<string> => {
	const secretKey = await crypto.subtle.importKey(
		'raw',
		new TextEncoder().encode(secret),
		{name: 'HMAC', hash: 'SHA-256'},
		false,
		['sign']
	)
	const sigBuf = await crypto.subtle.sign('HMAC', secretKey, new TextEncoder().encode(value))
	const signature = Buffer.from(sigBuf).toString('base64') // 44 chars, ends with "="
	return encodeURIComponent(`${value}.${signature}`)
}

/**
 * Mobile Login Exchange Endpoint
 * Allows unauthenticated mobile users to exchange a QR token for a session
 * The token was generated by an authenticated web user
 *
 * This is a standalone route (not in better-auth plugin) to avoid CSRF checks
 * which block requests without Origin headers (like mobile apps)
 */
export const POST = async (request: NextRequest) => {
	try {
		const body = await request.json()
		const {token} = body as {token: string}

		if (!token) {
			return NextResponse.json(
				{error: 'token is required'},
				{status: 400}
			)
		}

		// Verify the mobile login token
		const tokenData = verifyMobileLoginToken(token)

		if (!tokenData) {
			return NextResponse.json(
				{error: 'Invalid or expired token'},
				{status: 401}
			)
		}

		const userId = tokenData.userId

		// Verify the user exists
		const [user] = await db
			.select()
			.from(userTable)
			.where(eq(userTable.id, userId))
			.limit(1)

		if (!user) {
			return NextResponse.json(
				{error: 'User not found'},
				{status: 404}
			)
		}

		// Get request metadata
		const ipAddress = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
			|| request.headers.get('x-real-ip')
			|| ''
		const userAgent = request.headers.get('user-agent') || ''

		// Create session
		const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days
		const sessionToken = generateSecureToken(32)

		const [session] = await db.insert(sessionTable).values({
			userId,
			// IMPORTANT: Better Auth's internal adapter looks sessions up by the raw token.
			// The token is protected in transport by being a signed cookie.
			token: sessionToken,
			expiresAt,
			ipAddress,
			userAgent,
			createdAt: new Date(),
			updatedAt: new Date()
		}).returning()

		if (!session) {
			return NextResponse.json(
				{error: 'Failed to create session'},
				{status: 500}
			)
		}

		const secret = process.env.BETTER_AUTH_SECRET
		if (!secret) {
			console.error('BETTER_AUTH_SECRET not configured')
			return NextResponse.json({error: 'Server configuration error'}, {status: 500})
		}

		// This is the value that must be stored as the cookie value so `auth.api.getSession()`
		// can validate it via ctx.getSignedCookie().
		const signedSessionCookieValue = await signCookieValue(sessionToken, secret)
		const sessionCookieName = getCookies(auth.options).sessionToken.name

		return NextResponse.json({
			success: true,
			cookie: {
				// IMPORTANT: in production Better Auth prefixes cookies with "__Secure-"
				// so the actual cookie name is usually "__Secure-better-auth.session_token".
				name: sessionCookieName,
				value: signedSessionCookieValue,
				expiresAt: session.expiresAt
			},
			user: {
				id: user.id,
				email: user.email,
				name: user.name,
				image: user.image || null,
				emailVerified: user.emailVerified || false,
				createdAt: user.createdAt,
				updatedAt: user.updatedAt
			},
			session: {
				id: session.id,
				userId: session.userId,
				token: sessionToken,
				expiresAt: session.expiresAt,
				createdAt: session.createdAt,
				updatedAt: session.updatedAt
			},
			// Backwards compat (older clients stored this directly, which no longer works)
			token: sessionToken
		})
	} catch (error) {
		console.error('Error in mobile login exchange:', error)
		return NextResponse.json(
			{error: 'Failed to complete login'},
			{status: 500}
		)
	}
}

